tasks:
  - init: |
      cd $GITPOD_REPO_ROOT/react-app
      npm install # runs during prebuild
      npm install --save-dev --save-exact prettier
      npm install --global surge
    command: |
      cd $GITPOD_REPO_ROOT/react-app 
      npm start
  - command: |
      cd $GITPOD_REPO_ROOT/react-app ß
      node --version
      npm --version
      npm list
      npm list --global


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview