name: CI 
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use Node 16
        uses: actions/setup-node@v3
        with: 
            node-version: "16"
      - name: Install dependencies
        run: |
          cd react-app
          npm ci 
      - name: Check format
        run: |
          cd react-app
          npm format:check
      - name: Test
        run: |
          cd react-app
          npm test -- --coverage
        env:
          CI: true
        

    
          