name: Context testing
on: 
  push:
    branches:
      - chapter/03-1[7-9]
jobs:
  functions: 
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains( 'hello', '11' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', '1o' ) }}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!' ) }}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
        # this always runs
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        # next one will fail
      - name: Dump job context
        run: eccho '${{ toJSON(job) }}'
      - name: Dump steps context
        # This runs on failure
        if: failure()
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
        # The last one always runs
      - name: Dump matrix context
        if: always()
        run: echo '${{ toJSON(matrix) }}'