name: Matrix 
on: 
  push:
    branches:
      - chapter/04-20

jobs: 
  node-version:
    runs-on: ubuntu-latest
    steps: 
      - name: Log node version 
        run: node -v
      - uses: actions/setup-node@V1
        with:
          node-version: 6
      - name: Log node version 
        run: node -v