name: Notify on Release

on: 
  release:
    types:
      - "published"

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Release {{ github.event.release.tag_name }} is out, <{{ github.event.release.html_url}}|check it out now.> - triggered by $GITHUB_EVENT_NAME from $GITHUB_REPOSITORY."
