name: Notify on Release 2

on: 
  release:
    types:
      - "published"

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Release {{ github.event.release.tag_name }} is out, See {{ github.event.release.html_url }} "
